name: Markdown spell & grammar checks
on:
  push:
  pull_request:
    branches: [main]

jobs:
  spellandgrammarchecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell and grammar check check
      - run: pwd
      - run: sh ./MDSpellAndGrammarCheck.sh
