name: Markdown spell & grammar checks

jobs:
  spellandgrammarchecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell and grammar check check
      - run: sh ./MDSpellAndGrammarCheck.sh
